<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Initial schema of the documentation index (ADR-004): chronicle entries, architecture
 * decisions and their shared tags.
 *
 * The `search_vector` columns are filled by `docs:import` with
 * to_tsvector('german', ...) and are read through GIN indexes; a GIN index is what makes
 * `search_vector @@ plainto_tsquery(...)` fast, a default btree index would not be used
 * for that operator.
 */
final class Version20260907130502 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create doc_entry, doc_adr, doc_tag and the join tables incl. full-text indexes';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE doc_entry (
                id INT NOT NULL,
                slug VARCHAR(200) NOT NULL,
                title VARCHAR(255) NOT NULL,
                date DATE NOT NULL,
                type VARCHAR(32) NOT NULL,
                summary TEXT NOT NULL,
                agents JSONB NOT NULL,
                repos JSONB NOT NULL,
                adrs JSONB NOT NULL,
                learning_path INT DEFAULT NULL,
                body_markdown TEXT NOT NULL,
                body_html TEXT NOT NULL,
                imported_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                search_vector TSVECTOR DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_44C8F026989D9B62 ON doc_entry (slug)');
        $this->addSql('CREATE INDEX idx_doc_entry_date ON doc_entry (date)');
        $this->addSql('CREATE INDEX idx_doc_entry_search ON doc_entry USING GIN (search_vector)');

        $this->addSql(<<<'SQL'
            CREATE TABLE doc_adr (
                id VARCHAR(16) NOT NULL,
                slug VARCHAR(200) NOT NULL,
                title VARCHAR(255) NOT NULL,
                status VARCHAR(32) NOT NULL,
                date DATE NOT NULL,
                agents JSONB NOT NULL,
                supersedes VARCHAR(16) DEFAULT NULL,
                superseded_by VARCHAR(16) DEFAULT NULL,
                body_markdown TEXT NOT NULL,
                body_html TEXT NOT NULL,
                imported_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                search_vector TSVECTOR DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A04407CA989D9B62 ON doc_adr (slug)');
        $this->addSql('CREATE INDEX idx_doc_adr_search ON doc_adr USING GIN (search_vector)');

        $this->addSql(<<<'SQL'
            CREATE TABLE doc_tag (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(100) NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AA0376FF5E237E06 ON doc_tag (name)');

        $this->addSql('CREATE TABLE doc_entry_tag (doc_entry_id INT NOT NULL, doc_tag_id INT NOT NULL, PRIMARY KEY (doc_entry_id, doc_tag_id))');
        $this->addSql('CREATE INDEX IDX_CEDF584DB825419 ON doc_entry_tag (doc_entry_id)');
        $this->addSql('CREATE INDEX IDX_CEDF58438B57EBD ON doc_entry_tag (doc_tag_id)');

        $this->addSql('CREATE TABLE doc_adr_tag (doc_adr_id VARCHAR(16) NOT NULL, doc_tag_id INT NOT NULL, PRIMARY KEY (doc_adr_id, doc_tag_id))');
        $this->addSql('CREATE INDEX IDX_109E9F77C489C548 ON doc_adr_tag (doc_adr_id)');
        $this->addSql('CREATE INDEX IDX_109E9F7738B57EBD ON doc_adr_tag (doc_tag_id)');

        // ON DELETE CASCADE: removing a file removes its row, the join rows go with it.
        $this->addSql('ALTER TABLE doc_entry_tag ADD CONSTRAINT FK_CEDF584DB825419 FOREIGN KEY (doc_entry_id) REFERENCES doc_entry (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE doc_entry_tag ADD CONSTRAINT FK_CEDF58438B57EBD FOREIGN KEY (doc_tag_id) REFERENCES doc_tag (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE doc_adr_tag ADD CONSTRAINT FK_109E9F77C489C548 FOREIGN KEY (doc_adr_id) REFERENCES doc_adr (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE doc_adr_tag ADD CONSTRAINT FK_109E9F7738B57EBD FOREIGN KEY (doc_tag_id) REFERENCES doc_tag (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE doc_entry_tag DROP CONSTRAINT FK_CEDF584DB825419');
        $this->addSql('ALTER TABLE doc_entry_tag DROP CONSTRAINT FK_CEDF58438B57EBD');
        $this->addSql('ALTER TABLE doc_adr_tag DROP CONSTRAINT FK_109E9F77C489C548');
        $this->addSql('ALTER TABLE doc_adr_tag DROP CONSTRAINT FK_109E9F7738B57EBD');
        $this->addSql('DROP TABLE doc_entry_tag');
        $this->addSql('DROP TABLE doc_adr_tag');
        $this->addSql('DROP TABLE doc_entry');
        $this->addSql('DROP TABLE doc_adr');
        $this->addSql('DROP TABLE doc_tag');
    }
}
